apiVersion: v1
kind: PersistentVolume
metadata:
  name: parquet-lake-pv
spec:
  hostPath:
    path: /mnt/sesame-idam-data/parquet-lake
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - sesame-idam-control-plane
