{{- if and .Values.postgres.enabled (eq .Values.persistence.mode "staticPv") }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistence.postgres.pvName }}
  labels:
    {{- include "microscaler-supabase.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.persistence.postgres.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: {{ .Values.persistence.reclaimPolicy }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  hostPath:
    path: {{ .Values.persistence.postgres.hostPath }}
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - {{ .Values.persistence.nodeHostname | quote }}
{{- end }}
