{{- if .Values.postgresExporter.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  namespace: {{ include "microscaler-supabase.namespace" . }}
  labels:
    {{- include "microscaler-supabase.labels" . | nindent 4 }}
    app: postgres-exporter
  {{- with .Values.postgresExporter.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.postgresExporter.service.type | quote }}
  ports:
    - port: {{ .Values.postgresExporter.service.port }}
      targetPort: metrics
      name: metrics
  selector:
    app: postgres-exporter
{{- end }}
